database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password : "password"
  database_name: "newsletter"
application:
  port : 8000
email_client:
  base_url : "localhost"
  sender_email : "aymeric.sabrie@polytechnique.edu"
  authorization_token : "test"
  timeout_millisecond : 10000
redis_uri: "redis://127.0.0.1:6379"
